##
## EPITECH PROJECT, 2020
## Makefile graph lib
## File description:
## Makefile
##

all:
	make -C ./ncurses
	make -C ./Sfml
	make -C ./Sdl

clean:
	make clean -C ./ncurses
	make clean -C ./Sfml
	make clean -C ./Sdl

fclean:
	make fclean -C ./ncurses
	make fclean -C ./Sfml
	make fclean -C ./Sdl/

re:
	fclean all

.PHONY:
	all clean fclean re
